services:
  traefik:
    ports:
      - "8080:8080"
    environment:
      - "TRAEFIK_API_INSECURE=true" # Enable insecure API/Dashboard on port 8080

    deploy:
      labels:
        - "traefik.http.routers.traefik-dashboard.tls=true"

  portainer:
    ports:
      - "9000:9000"
    deploy:
      labels:
        - "traefik.http.routers.portainer.tls=true"
