name: Deploy to Gaia

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: [self-hosted, gaia]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Deploy with start.sh
        env:
          TUNNEL_TOKEN: ${{ secrets.TUNNEL_TOKEN }}
          CLOUDFLARE_DOMAIN: ${{ vars.DOMAIN_NAME }}
          TRAEFIK_SUBDOMAIN: ${{ vars.TRAEFIK_SUBDOMAIN }}
          PORTAINER_SUBDOMAIN: ${{ vars.PORTAINER_SUBDOMAIN }}
          CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
          CF_DNS_API_TOKEN: ${{ secrets.CF_DNS_API_TOKEN }}
        run: |
          chmod +x start.sh
          ./start.sh