name: Deploy to Gaia

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Deploy with start.sh
        env:
          TUNNEL_TOKEN: ${{ secrets.TUNNEL_TOKEN }}
          CLOUDFLARE_DOMAIN: ${{ vars.DOMAIN_NAME }}
          TRAEFIK_SUBDOMAIN: ${{ vars.TRAEFIK_SUBDOMAIN }}
          PORTAINER_SUBDOMAIN: ${{ vars.PORTAINER_SUBDOMAIN }}
          CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
          CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}
        run: |
          chmod +x start.sh
          ./start.sh